/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author aylee
 */
public class Detalles extends javax.swing.JPanel {

    /**
     * Creates new form Detalles
     */
    public Detalles() {
        initComponents();
    }
    
    public void cargarFotos(ArrayList<String> rutasFotos) {
    panel_fotos.removeAll(); 

    panel_fotos.setLayout(new BoxLayout(panel_fotos, BoxLayout.Y_AXIS));

    for (String ruta : rutasFotos) {
        ImageIcon img = new ImageIcon(ruta);
        Image image = img.getImage().getScaledInstance(250, 180, Image.SCALE_SMOOTH);

        JLabel foto = new JLabel(new ImageIcon(image));
        foto.setPreferredSize(new Dimension(250, 180));
        foto.setMaximumSize(new Dimension(250, 180));
        foto.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Separación entre fotos (margen)
        foto.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));

        panel_fotos.add(foto);
    }

    panel_fotos.revalidate();
    panel_fotos.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDireccion_vivienda7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtADescripcion_vivienda = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_fotos = new javax.swing.JPanel();
        txtDireccion_vivienda = new javax.swing.JTextField();
        txtPais_vivienda = new javax.swing.JTextField();
        txtTipo_vivienda = new javax.swing.JTextField();
        txtBaños_vivienda = new javax.swing.JTextField();
        txtHabitaciones_vivienda = new javax.swing.JTextField();
        txtCiudad_vivienda = new javax.swing.JTextField();
        txtPiscina_vivienda = new javax.swing.JTextField();
        txtBarrio_vivienda = new javax.swing.JTextField();
        txtConjunto_vivienda = new javax.swing.JTextField();
        txtMascotas_vivienda = new javax.swing.JTextField();
        txtMovilidad_vivienda = new javax.swing.JTextField();
        txtParrilla_vivienda = new javax.swing.JTextField();
        txtAgua_vivienda = new javax.swing.JTextField();
        txtBalcon_vivienda = new javax.swing.JTextField();
        txtParques_vivienda = new javax.swing.JTextField();
        txtCapacidad_vivienda = new javax.swing.JTextField();
        txtPrecio_vivienda = new javax.swing.JTextField();
        txtVigilancia_vivienda = new javax.swing.JTextField();

        txtDireccion_vivienda7.setEditable(false);
        txtDireccion_vivienda7.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion_vivienda7.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(828, 775));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ebrima", 3, 20)); // NOI18N
        jLabel4.setText("DETALLE DE LA PUBLICACION");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 19, 290, 30));

        jLabel27.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel27.setText("Pais donde esta ubicada:");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 180, 20));

        jLabel12.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel12.setText("Ciudad donde esta ubicada");
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 190, 20));

        jLabel17.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel17.setText("Barrio donde esta ubicada:");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 190, 20));

        jLabel21.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel21.setText("Direccion:");
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, 20));

        jLabel7.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel7.setText("Capacidad maxima:");
        jPanel14.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 180, 20));

        jLabel31.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel31.setText("numero de habitaciones:");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 180, 20));

        jLabel30.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel30.setText("numero de baños:");
        jPanel14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 180, 20));

        jLabel29.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel29.setText("Tipo de vivienda:");
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 130, 20));

        jLabel32.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel32.setText("Precio por noche:");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 190, 20));

        jLabel38.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel38.setText("Pequeña descripcion:");
        jPanel14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 180, 20));

        txtADescripcion_vivienda.setColumns(20);
        txtADescripcion_vivienda.setRows(5);
        jScrollPane6.setViewportView(txtADescripcion_vivienda);

        jPanel14.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 220, 100));

        jLabel34.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel34.setText("FOTOS");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 20));

        jLabel37.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel37.setText("¿Tiene piscina?");
        jPanel14.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 770, 130, 20));

        jLabel39.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel39.setText("¿Tiene parrilla?");
        jPanel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 130, 20));

        jLabel40.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel40.setText("¿Se permiten mascotas?");
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, 170, 20));

        jLabel48.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel48.setText("¿Tiene parque ");
        jPanel14.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 110, 20));

        jLabel41.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel41.setText("o zonas verdes?");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 110, 20));

        jLabel42.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel42.setText("¿Tiene balcon?");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 130, 20));

        jLabel43.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel43.setText("¿Tiene calefaccion?");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 160, 20));

        jLabel50.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel50.setText("¿Tiene acceso para ");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 680, 140, -1));

        jLabel51.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel51.setText("personas con movilidad");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 700, 170, -1));

        jLabel49.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel49.setText("reducida o dificultada?");
        jPanel14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 170, -1));

        jLabel47.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel47.setText("¿Cuenta con vigilancia ");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, -1, 20));

        jLabel44.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel44.setText("o zona de porteria?");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 780, 140, -1));

        jLabel46.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel46.setText("¿Esta dentro de un");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 140, -1));

        jLabel45.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel45.setText("conjunto cerrado?");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 140, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 190));

        panel_fotos.setBackground(new java.awt.Color(255, 255, 255));
        panel_fotos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_fotosLayout = new javax.swing.GroupLayout(panel_fotos);
        panel_fotos.setLayout(panel_fotosLayout);
        panel_fotosLayout.setHorizontalGroup(
            panel_fotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        panel_fotosLayout.setVerticalGroup(
            panel_fotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panel_fotos);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtDireccion_vivienda.setEditable(false);
        txtDireccion_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccion_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtDireccion_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 810, -1));

        txtPais_vivienda.setEditable(false);
        txtPais_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtPais_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtPais_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 220, -1));

        txtTipo_vivienda.setEditable(false);
        txtTipo_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtTipo_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 220, -1));

        txtBaños_vivienda.setEditable(false);
        txtBaños_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtBaños_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtBaños_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 220, -1));

        txtHabitaciones_vivienda.setEditable(false);
        txtHabitaciones_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtHabitaciones_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtHabitaciones_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 220, -1));

        txtCiudad_vivienda.setEditable(false);
        txtCiudad_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudad_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtCiudad_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 220, -1));

        txtPiscina_vivienda.setEditable(false);
        txtPiscina_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtPiscina_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtPiscina_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 810, 220, -1));

        txtBarrio_vivienda.setEditable(false);
        txtBarrio_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtBarrio_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtBarrio_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 220, -1));

        txtConjunto_vivienda.setEditable(false);
        txtConjunto_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtConjunto_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtConjunto_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 220, -1));

        txtMascotas_vivienda.setEditable(false);
        txtMascotas_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtMascotas_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtMascotas_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 710, 220, -1));

        txtMovilidad_vivienda.setEditable(false);
        txtMovilidad_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtMovilidad_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtMovilidad_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 760, 220, -1));

        txtParrilla_vivienda.setEditable(false);
        txtParrilla_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtParrilla_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtParrilla_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 220, -1));

        txtAgua_vivienda.setEditable(false);
        txtAgua_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtAgua_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtAgua_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 220, -1));

        txtBalcon_vivienda.setEditable(false);
        txtBalcon_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtBalcon_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtBalcon_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 220, -1));

        txtParques_vivienda.setEditable(false);
        txtParques_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtParques_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtParques_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 220, -1));

        txtCapacidad_vivienda.setEditable(false);
        txtCapacidad_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtCapacidad_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtCapacidad_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, -1));

        txtPrecio_vivienda.setEditable(false);
        txtPrecio_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtPrecio_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 220, -1));

        txtVigilancia_vivienda.setEditable(false);
        txtVigilancia_vivienda.setBackground(new java.awt.Color(255, 255, 255));
        txtVigilancia_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtVigilancia_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 220, -1));

        jScrollPane1.setViewportView(jPanel14);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panel_fotos;
    private javax.swing.JTextArea txtADescripcion_vivienda;
    private javax.swing.JTextField txtAgua_vivienda;
    private javax.swing.JTextField txtBalcon_vivienda;
    private javax.swing.JTextField txtBarrio_vivienda;
    private javax.swing.JTextField txtBaños_vivienda;
    private javax.swing.JTextField txtCapacidad_vivienda;
    private javax.swing.JTextField txtCiudad_vivienda;
    private javax.swing.JTextField txtConjunto_vivienda;
    private javax.swing.JTextField txtDireccion_vivienda;
    private javax.swing.JTextField txtDireccion_vivienda7;
    private javax.swing.JTextField txtHabitaciones_vivienda;
    private javax.swing.JTextField txtMascotas_vivienda;
    private javax.swing.JTextField txtMovilidad_vivienda;
    private javax.swing.JTextField txtPais_vivienda;
    private javax.swing.JTextField txtParques_vivienda;
    private javax.swing.JTextField txtParrilla_vivienda;
    private javax.swing.JTextField txtPiscina_vivienda;
    private javax.swing.JTextField txtPrecio_vivienda;
    private javax.swing.JTextField txtTipo_vivienda;
    private javax.swing.JTextField txtVigilancia_vivienda;
    // End of variables declaration//GEN-END:variables
}
