/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author aylee
 */
public class menu_main extends javax.swing.JFrame {

    /**
     * Creates new form login_main
     */
    public menu_main() {
        initComponents();
        setLocationRelativeTo(null);
        //cargarPublicaciones();
        panel_menu_extendido.setVisible(false);
        panel_menu_recojido.setVisible(true);     
    }
    
   public void animarPanel(JPanel panel, int widthInicial, int widthFinal) {
    new Thread(() -> {
        try {
            if (widthInicial < widthFinal) {
                // Expandir
                for (int i = widthInicial; i <= widthFinal; i++) {
                    Thread.sleep(2);
                    panel.setSize(i, panel.getHeight());
                }
            } else {
                // Contraer
                for (int i = widthInicial; i >= widthFinal; i--) {
                    Thread.sleep(2);
                    panel.setSize(i, panel.getHeight());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }).start();
    }
   
   /*private void cargarPublicaciones() {

    panel_publicaciones.setLayout(new BoxLayout(panel_publicaciones, BoxLayout.Y_AXIS));

    for (Publicacion p : listaPublicaciones) {

        panel_publicaciones publicacion = new panel_publicaciones(); // tu panel diseñado

        // LE PASAMOS LOS DATOS A LA CARD
        publicacion.setTitulo(p.getTitulo());
        publicacion.setPrecio(p.getPrecio());
        publicacion.setPais(p.getPais());
        publicacion.setCiudad(p.getCiudad());
        publicacion.setBarrio(p.getBarrio());
        publicacion.setDireccion(p.getDireccion());
        publicacion.setImagen(p.getRutaImagen());

        panel_publicaciones.add(card);
        panel_publicaciones.add(Box.createVerticalStrut(10));
    }

    panel_publicaciones.revalidate();
    panel_publicaciones.repaint();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        boton_menu = new javax.swing.JLabel();
        panel_menu_recojido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        crear_publicacion = new javax.swing.JLabel();
        bandeja_entrada = new javax.swing.JLabel();
        mis_publicaciones = new javax.swing.JLabel();
        reservas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_crear_publicaciones = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        panel_bandeja = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cbPais_vivienda = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbCiudad_vivienda = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtBarrio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDireccion_vivienda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jsCapacidad = new com.toedter.components.JSpinField();
        jLabel31 = new javax.swing.JLabel();
        jsHabitaciones = new com.toedter.components.JSpinField();
        jLabel30 = new javax.swing.JLabel();
        jsBaños = new com.toedter.components.JSpinField();
        jLabel29 = new javax.swing.JLabel();
        cbTipo_vivienda = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        Fotos = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbVista_Previa = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cbPiscina = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        cbParrilla = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        cbMascotas = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cbParques = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        cbBalcon = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        cbAgua = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        cb_movilidad = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        cb_vigilancia = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        cbConjunto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        panel_mis_publicaciones = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        panel_reservas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        panel_favoritos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        panel_menu_extendido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_menu.setBackground(new java.awt.Color(255, 255, 255));
        boton_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        boton_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_menuMouseClicked(evt);
            }
        });
        menu.add(boton_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        panel_menu_recojido.setBackground(new java.awt.Color(255, 255, 255));
        panel_menu_recojido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_menu_recojido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_menu_recojido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        crear_publicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-mas (2).png"))); // NOI18N
        crear_publicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crear_publicacionMouseClicked(evt);
            }
        });
        panel_menu_recojido.add(crear_publicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        bandeja_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hogar (3).png"))); // NOI18N
        bandeja_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bandeja_entradaMouseClicked(evt);
            }
        });
        panel_menu_recojido.add(bandeja_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 50));

        mis_publicaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llave (1)_1.png"))); // NOI18N
        mis_publicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mis_publicacionesMouseClicked(evt);
            }
        });
        panel_menu_recojido.add(mis_publicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 70, 60));

        reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario (1).png"))); // NOI18N
        reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasMouseClicked(evt);
            }
        });
        panel_menu_recojido.add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, 50));

        jPanel1.add(panel_menu_recojido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        panel_crear_publicaciones.setBackground(new java.awt.Color(255, 255, 255));
        panel_crear_publicaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel4);

        panel_crear_publicaciones.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        jTabbedPane1.addTab("tab1", panel_crear_publicaciones);

        panel_bandeja.setBackground(new java.awt.Color(255, 255, 255));
        panel_bandeja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(828, 775));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ebrima", 3, 20)); // NOI18N
        jLabel4.setText("CREAR PUBLICACION");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 19, 210, 30));

        jLabel27.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel27.setText("Pais donde esta ubicada:");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, 20));

        jPanel14.add(cbPais_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, -1));

        jLabel12.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel12.setText("Ciudad donde esta ubicada");
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, 20));

        jPanel14.add(cbCiudad_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, -1));

        jLabel17.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel17.setText("Barrio donde esta ubicada:");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, 20));

        txtBarrio.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, -1));

        jLabel21.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel21.setText("Direccion:");
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 180, 20));

        txtDireccion_vivienda.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtDireccion_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 180, -1));

        jLabel7.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel7.setText("Capacidad maxima:");
        jPanel14.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 20));
        jPanel14.add(jsCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 170, 30));

        jLabel31.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel31.setText("numero de habitaciones:");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 180, 20));
        jPanel14.add(jsHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 170, 30));

        jLabel30.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel30.setText("numero de baños:");
        jPanel14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 20));
        jPanel14.add(jsBaños, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 170, 30));

        jLabel29.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel29.setText("Tipo de vivienda:");
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 130, 20));

        jPanel14.add(cbTipo_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 170, 30));

        jLabel32.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel32.setText("Precio por noche:");
        jPanel14.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 190, 20));

        txtPrecio.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        jPanel14.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 220, -1));

        jLabel38.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel38.setText("Pequeña descripcion:");
        jPanel14.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 180, 20));

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane6.setViewportView(taDescripcion);

        jPanel14.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 220, 100));

        Fotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        Fotos.setText("jLabel2");
        Fotos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel14.add(Fotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 70, 70));

        jLabel34.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel34.setText("Añadir fotos");
        jPanel14.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 90, 20));

        lbVista_Previa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel14.add(lbVista_Previa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 130, 100));

        jLabel37.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel37.setText("¿Tiene piscina?");
        jPanel14.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 130, 20));

        cbPiscina.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cbPiscina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cbPiscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 170, -1));

        jLabel39.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel39.setText("¿Tiene parrilla?");
        jPanel14.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 130, 20));

        cbParrilla.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cbParrilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cbParrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 170, -1));

        jLabel40.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel40.setText("¿Se permiten mascotas?");
        jPanel14.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 170, -1));

        cbMascotas.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cbMascotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cbMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 170, -1));

        jLabel48.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel48.setText("¿Tiene parque ");
        jPanel14.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 110, 20));

        jLabel41.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel41.setText("o zonas verdes?");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 110, 20));

        cbParques.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cbParques.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cbParques, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 170, -1));

        jLabel42.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel42.setText("¿Tiene balcon?");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 130, 20));

        cbBalcon.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cbBalcon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cbBalcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, 170, -1));

        jLabel43.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel43.setText("¿Tiene calefaccion?");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 160, 20));

        cbAgua.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cbAgua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cbAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 170, -1));

        jLabel50.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel50.setText("¿Tiene acceso para ");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 140, -1));

        jLabel51.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel51.setText("personas con movilidad");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 170, -1));

        jLabel49.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel49.setText("reducida o dificultada?");
        jPanel14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 170, -1));

        cb_movilidad.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cb_movilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cb_movilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 170, 30));

        jLabel47.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel47.setText("¿Cuenta con vigilancia ");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, 20));

        jLabel44.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel44.setText("o zona de porteria?");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 140, -1));

        cb_vigilancia.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cb_vigilancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cb_vigilancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 170, 30));

        jLabel46.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel46.setText("¿Esta dentro de un");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 140, -1));

        jLabel45.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel45.setText("conjunto cerrado?");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 140, -1));

        cbConjunto.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        cbConjunto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel14.add(cbConjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 170, 30));

        jButton1.setFont(new java.awt.Font("Ebrima", 3, 17)); // NOI18N
        jButton1.setText("PUBLICAR");
        jButton1.setBorder(null);
        jPanel14.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 723, 120, 30));

        jScrollPane2.setViewportView(jPanel14);

        panel_bandeja.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        jTabbedPane1.addTab("tab2", panel_bandeja);

        panel_mis_publicaciones.setBackground(new java.awt.Color(255, 255, 255));
        panel_mis_publicaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane4.setViewportView(jPanel8);

        panel_mis_publicaciones.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 560));

        jTabbedPane1.addTab("tab3", panel_mis_publicaciones);

        panel_reservas.setBackground(new java.awt.Color(255, 255, 255));
        panel_reservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel3);

        panel_reservas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        jTabbedPane1.addTab("tab4", panel_reservas);

        panel_favoritos.setBackground(new java.awt.Color(255, 255, 255));
        panel_favoritos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane5.setViewportView(jPanel10);

        panel_favoritos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        jTabbedPane1.addTab("tab5", panel_favoritos);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 830, 590));

        panel_menu_extendido.setBackground(new java.awt.Color(255, 255, 255));
        panel_menu_extendido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_menu_extendido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-mas (2).png"))); // NOI18N
        jLabel2.setText("CREAR PUBLICACION");
        panel_menu_extendido.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 60));

        jLabel5.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hogar (3).png"))); // NOI18N
        jLabel5.setText("INICIO");
        panel_menu_extendido.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 50));

        jLabel6.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llave (1)_1.png"))); // NOI18N
        jLabel6.setText("PUBLICACIONES");
        panel_menu_extendido.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 60));

        jLabel3.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario (1).png"))); // NOI18N
        jLabel3.setText("RESERVAS");
        panel_menu_extendido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 210, 50));

        jPanel1.add(panel_menu_extendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_menuMouseClicked
        if (panel_menu_extendido.isVisible()) {
        
        animarPanel(panel_menu_extendido, 220, 220);

        panel_menu_extendido.setVisible(false);
        panel_menu_recojido.setVisible(true);

    } else {
        panel_menu_extendido.setVisible(true);
        panel_menu_recojido.setVisible(false);

        animarPanel(panel_menu_extendido, 70, 220);
    }
    }//GEN-LAST:event_boton_menuMouseClicked

    private void crear_publicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crear_publicacionMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_crear_publicacionMouseClicked

    private void bandeja_entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bandeja_entradaMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_bandeja_entradaMouseClicked

    private void mis_publicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mis_publicacionesMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_mis_publicacionesMouseClicked

    private void reservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_reservasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fotos;
    private javax.swing.JLabel bandeja_entrada;
    private javax.swing.JLabel boton_menu;
    private javax.swing.JComboBox<String> cbAgua;
    private javax.swing.JComboBox<String> cbBalcon;
    private javax.swing.JComboBox<String> cbCiudad_vivienda;
    private javax.swing.JComboBox<String> cbConjunto;
    private javax.swing.JComboBox<String> cbMascotas;
    private javax.swing.JComboBox<String> cbPais_vivienda;
    private javax.swing.JComboBox<String> cbParques;
    private javax.swing.JComboBox<String> cbParrilla;
    private javax.swing.JComboBox<String> cbPiscina;
    private javax.swing.JComboBox<String> cbTipo_vivienda;
    private javax.swing.JComboBox<String> cb_movilidad;
    private javax.swing.JComboBox<String> cb_vigilancia;
    private javax.swing.JLabel crear_publicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.components.JSpinField jsBaños;
    private com.toedter.components.JSpinField jsCapacidad;
    private com.toedter.components.JSpinField jsHabitaciones;
    private javax.swing.JLabel lbVista_Previa;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel mis_publicaciones;
    private javax.swing.JPanel panel_bandeja;
    private javax.swing.JPanel panel_crear_publicaciones;
    private javax.swing.JPanel panel_favoritos;
    private javax.swing.JPanel panel_menu_extendido;
    private javax.swing.JPanel panel_menu_recojido;
    private javax.swing.JPanel panel_mis_publicaciones;
    private javax.swing.JPanel panel_reservas;
    private javax.swing.JLabel reservas;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtDireccion_vivienda;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
