/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author aylee
 */
public class panel_publicaciones extends javax.swing.JPanel {

    /**
     * Creates new form panel_publicaciones
     */
    public panel_publicaciones() {
        initComponents();
    }
   
    
    public void setTitulo(String titulo) {
        titulo_alojamiento.setText(titulo);
    }

    public void setPrecio(String precio) {
        precio_alojamiento.setText(precio);
    }

    public void setPais(String pais) {
        barrio_alojamiento.setText(pais);
    }

    public void setCiudad(String ciudad) {
        ciudad_alojamiento.setText(ciudad);
    }

    public void setBarrio(String barrio) {
        barrio_alojamiento.setText(barrio);
    }

    public void setDireccion(String direccion) {
        direccion_alojamiento.setText(direccion);
    }

   public void setImagen(String ruta) {
        ImageIcon icon = new ImageIcon(ruta);
        Image img = icon.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH);
        foto_alojamiento.setIcon(new ImageIcon(img));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_alojamientos = new javax.swing.JPanel();
        direccion_alojamiento = new javax.swing.JLabel();
        foto_alojamiento = new javax.swing.JLabel();
        titulo_alojamiento = new javax.swing.JLabel();
        barrio_alojamiento = new javax.swing.JLabel();
        precio_alojamiento = new javax.swing.JLabel();
        ciudad_alojamiento = new javax.swing.JLabel();
        pais_alojamiento = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_alojamientos.setBackground(new java.awt.Color(255, 255, 255));
        panel_alojamientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panel_alojamientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        direccion_alojamiento.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        direccion_alojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_alojamientos.add(direccion_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 400, 30));

        foto_alojamiento.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        foto_alojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_alojamientos.add(foto_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 130));

        titulo_alojamiento.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        titulo_alojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_alojamientos.add(titulo_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 650, 30));

        barrio_alojamiento.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        barrio_alojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_alojamientos.add(barrio_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 240, 30));

        precio_alojamiento.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        precio_alojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_alojamientos.add(precio_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, 30));

        ciudad_alojamiento.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        ciudad_alojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_alojamientos.add(ciudad_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 210, 30));

        pais_alojamiento.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        pais_alojamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_alojamientos.add(pais_alojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 220, 30));

        jPanel1.add(panel_alojamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barrio_alojamiento;
    private javax.swing.JLabel ciudad_alojamiento;
    private javax.swing.JLabel direccion_alojamiento;
    private javax.swing.JLabel foto_alojamiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pais_alojamiento;
    private javax.swing.JPanel panel_alojamientos;
    private javax.swing.JLabel precio_alojamiento;
    private javax.swing.JLabel titulo_alojamiento;
    // End of variables declaration//GEN-END:variables
}
