/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Model.Alojamiento;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author aylee
 */
public class reservar extends javax.swing.JPanel {

    /**
     * Creates new form reservar
     */
    public reservar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        dcEntrada = new com.toedter.calendar.JDateChooser();
        jLabel81 = new javax.swing.JLabel();
        dcSalida = new com.toedter.calendar.JDateChooser();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        txtLugar_reserva = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cbPais_vivienda = new javax.swing.JComboBox<>();
        cbPais_vivienda1 = new javax.swing.JComboBox<>();
        jLabel85 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jLabel73.setText("RESERVAR");
        add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 140, 40));

        jLabel74.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel74.setText("Lugar de la reserva:");
        add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 20));

        jLabel75.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel75.setText("Documento:");
        add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 20));

        jLabel76.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel76.setText("Nombre:");
        add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 140, 20));

        jLabel77.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel77.setText("Apellido:");
        add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 140, 20));

        jLabel78.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campana.png"))); // NOI18N
        jLabel78.setText("RESERVAR");
        jLabel78.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 120, 30));

        jLabel79.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel79.setText("Correo electronico:");
        add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 140, 20));

        jLabel80.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel80.setText("Dia de entrada:");
        add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 140, 20));
        add(dcEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 230, 30));

        jLabel81.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel81.setText("Dia de salida:");
        add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 140, 20));
        add(dcSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 230, 30));

        jLabel82.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel82.setText("Telefono:");
        add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 140, 20));

        jLabel83.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel83.setText("Hora de entrada:");
        add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 140, 20));

        jLabel84.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel84.setText("Hora de salida:");
        add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 140, 20));

        txtLugar_reserva.setEditable(false);
        txtLugar_reserva.setBackground(new java.awt.Color(255, 255, 255));
        txtLugar_reserva.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        add(txtLugar_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, -1));

        txtDocumento.setEditable(false);
        txtDocumento.setBackground(new java.awt.Color(255, 255, 255));
        txtDocumento.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 220, -1));

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 220, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 220, -1));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Ebrima", 2, 14)); // NOI18N
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 220, -1));

        cbPais_vivienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3:00", "3:30", "4:00", "4:30", "5:00", "5:30", "6:00", "6:30" }));
        add(cbPais_vivienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 180, -1));

        cbPais_vivienda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "12:30", "1:00", "1:30", "2:00" }));
        add(cbPais_vivienda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 180, -1));

        jLabel85.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha-hacia-atras-peque.png"))); // NOI18N
        jLabel85.setText("VOLVER");
        jLabel85.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel85.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel85MouseClicked(evt);
            }
        });
        add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel85MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel85MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel85MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPais_vivienda;
    private javax.swing.JComboBox<String> cbPais_vivienda1;
    private com.toedter.calendar.JDateChooser dcEntrada;
    private com.toedter.calendar.JDateChooser dcSalida;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLugar_reserva;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
